In [3]:
aList = ["Ari",20,"Tangerang Selatan", True]

In [4]:
aList

['Ari', 20, 'Tangerang Selatan', True]

In [5]:
type(aList)

list

In [10]:
bin_colors=['Blue','Green','White','Gray']

In [11]:
bin_colors=['Blue','Green','White','Gray']
print(f"The second element of the tuple is {bin_colors[1]}")

The second element of the tuple is Green


In [13]:
print(f"The elements after third element onwards are {bin_colors[2:]}")

The elements after third element onwards are ['White', 'Gray']


In [15]:
nested_tuple = (1,2,(100,200,300),6)
print(f"The maximum value of the inner tuple {max(nested_tuple[2])}")

The maximum value of the inner tuple 300


In [41]:
bin_colors ={
    "manual_color" : "Yellow",
    "approved_color" : "Green",
    "refused_color" : "Red"
}

In [42]:
print(bin_colors)

{'manual_color': 'Yellow', 'approved_color': 'Green', 'refused_color': 'Red'}


In [43]:
bin_colors.get('approved_color')

'Green'

In [44]:
bin_colors['approved_color']

'Green'

In [45]:
bin_colors['approved_color']="Purple"

In [46]:
print(bin_colors)

{'manual_color': 'Yellow', 'approved_color': 'Purple', 'refused_color': 'Red'}


In [47]:
green = {'grass', 'leaves'}
print(green)

{'grass', 'leaves'}


In [49]:
yellow = {'dandelions', 'fire hydrant', 'leaves'}
red = {'fire hydrant', 'blood', 'rose', 'leaves'}

In [51]:
print(f"The intersaction of yellow and red is {yellow&red}")

The intersaction of yellow and red is {'leaves', 'fire hydrant'}


In [60]:
import pandas as pd
df = pd.DataFrame([
    ['1', 'Daffa', 32, True],
    ['2', 'Ari', 22, False],
    ['3', 'Rara', 40, True]])
df.columns = ['id', 'name', 'age', 'decision']
print(df)

  id   name  age  decision
0  1  Daffa   32      True
1  2    Ari   22     False
2  3   Rara   40      True


In [61]:
df[['name','age']]

name  age
0  Daffa   32
1    Ari   22
2   Rara   40

In [62]:
df.iloc[:,3]

0     True
1    False
2     True
Name: decision, dtype: bool

In [63]:
df.iloc[1:3,:]

id  name  age  decision
1  2   Ari   22     False
2  3  Rara   40      True

In [65]:
df[df.age>30]

id   name  age  decision
0  1  Daffa   32      True
2  3   Rara   40      True

In [66]:
import numpy as np
myMatrix = np.array([[11,12,13], [21,22,23], [31,32,33]])

In [67]:
print(myMatrix)

[[11 12 13]
 [21 22 23]
 [31 32 33]]


In [68]:
print(type(myMatrix))

<class 'numpy.ndarray'>


In [69]:
myMatrix.transpose()

array([[11, 21, 31],
       [12, 22, 32],
       [13, 23, 33]])

In [70]:
myVector = [22,33,44,55]
print(myVector)

[22, 33, 44, 55]


In [71]:
print(type(myVector))

<class 'list'>


In [72]:
myVector = np.array([22,33,44,55])
print(myVector)

[22 33 44 55]


In [73]:
print(type(myVector))

<class 'numpy.ndarray'>


In [75]:
class Stack:
    def __init__(self):
        self.items = []
    def isEmpty(self):
        return self.items == []
    def push(self, item):
        self.items.append(item)
    def pop(self):
        return self.items.pop()
    def peek(self):
        return self.items[len(self.items)-1]
    def size(self):
        return len(self.items)

In [76]:
stack=Stack()
stack.push('Red')
stack.push('Green')
stack.push("Blue")
stack.push("Yellow")

In [77]:
stack.pop()

'Yellow'

In [78]:
stack.isEmpty()

False

In [79]:
colors = ['Red']

In [80]:
colors.append('Green')
colors.append('Yellow')
colors.append('Blue')

In [81]:
colors

['Red', 'Green', 'Yellow', 'Blue']

In [82]:
class Queue(object):
    def __init__(self):
        self.items = []
    def isEmpty(self):
        return self.items == []
    def enqueue(self, item):
        self.items.insert(0,item)
    def dequeue(self):
        return self.items.pop()
    def size(self):
        return len(self.items)

In [83]:
queue = Queue()

In [84]:
queue.enqueue("Red")

In [85]:
queue.enqueue('Green')

In [86]:
queue.enqueue('Blue')

In [87]:
queue.enqueue('Yellow')

In [88]:
print(f"Size of queue is {queue.size()}")

Size of queue is 4


In [89]:
print(queue.dequeue())

Red
